### ISSUE TITLE
Does it always redirect for layers?

### ISSUE THREAD

**Issue by philipsparrow** [ahmetb/serverless-registry-proxy#45]
I tried deploying this in Cloud Run with a custom domain and it works great.
But when I try to pull images from a VM sitting behind an HTTP proxy (only allowing traffic to my custom domain), my client (`crictl`) throws this error:

```
FATA[0000] pulling image: rpc error:
code = Unknown
desc = failed to pull and unpack image "<mydomain>/images/<image>:<imagetag>":
failed to copy: httpReadSeeker: failed open: failed to do request:
Get "https://us-central1-docker.pkg.dev/artifacts-downloads/namespaces/<mygcpprojectid>/repositories/<myartifactregistryname>/downloads/<encodedtext>": Forbidden 
```

It looks like it's trying to pull the layers from the registry directly (pulling from us-central1-docker.pkg.dev rather than mydomain).

I tried adding/removing envvar `DISABLE_BROWSER_REDIRECTS="true"` to the CloudRun Service but the problem persists.

Perhaps I'm misunderstanding something about how `serverless-registry-proxy` works? I thought it was a pull-through proxy, but it feels like it's doing a redirect for the actual layers.

_Edit: formatting_

**Comment by ahmetb** [comment]
No, it serves the responses that the underlying registry serves as is.
