### ISSUE TITLE
Bypass proxy for blob layer requests to upstream GCP artifact registry (and save money)

### ISSUE THREAD

**Issue by dominik-lekse** [ahmetb/serverless-registry-proxy#8]
When the upstream registry is a GCP artifact registry, layer blobs pass through the proxy which causes billable networking egress and execution time for Cloud Run.

Similar to a GCR proxy, the registry client could be redirected directly to the upstream GCP artifact registry and thus by-pass the proxy for layer blob traffic.

### Description

- When the registry client requests a layer blob from AR, the AR responds with an `302 Found` to a location of the form `/artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/[1068 characters which appear to be a url base64 encoded signature and is assumed to authorize the get of the layer blob]`
- From the redirect target, a client can download the blob without the `Authorization` header
- Therefore, the assumption is that the urlbase64 encoded character sequence is a signature (similar)

- The `serverless-registry-proxy` can modify the response from the upstream AR and rewrite the `Location` before responding to the client
- To bypass the proxy in the subsequence layer blob request, the proxy prepends the host of the upstream AR to the `Location` header

Example:
- Location (by upstream AR): `/artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/...`
- Location (to client): `https://europe-west3-docker.pkg.dev/artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/...`

The following (shortened) log has been observed from a `crane blob -v` to a `*-docker.pkg.dev` AR.

```
2020/12/21 18:14:31 --> GET https://europe-west3-docker.pkg.dev/v2/neuspaces/neuspaces/go-httpbin/blobs/sha256:24f0c933cbef83faee52f82c7f889c727b1ece5123b92d036c52fa865480f037 [body redacted: omitting binary blobs from logs]
2020/12/21 18:14:31 GET /v2/neuspaces/neuspaces/go-httpbin/blobs/sha256:24f0c933cbef83faee52f82c7f889c727b1ece5123b92d036c52fa865480f037 HTTP/1.1
Host: europe-west3-docker.pkg.dev
User-Agent: go-containerregistry
Authorization: <redacted>
Accept-Encoding: gzip

2020/12/21 18:14:31 <-- 302 https://europe-west3-docker.pkg.dev/v2/neuspaces/neuspaces/go-httpbin/blobs/sha256:24f0c933cbef83faee52f82c7f889c727b1ece5123b92d036c52fa865480f037 (171.810544ms) [body redacted: omitting binary blobs from logs]
2020/12/21 18:14:31 HTTP/2.0 302 Found
Content-Length: 1166
Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Type: text/html; charset=utf-8
Date: Mon, 21 Dec 2020 17:14:31 GMT
Docker-Distribution-Api-Version: registry/2.0
Location: /artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/[1068 characters which appear to be a url base64 encoded signature and is assumed to authorize the get of the layer blob]
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

2020/12/21 18:14:31 --> GET https://europe-west3-docker.pkg.dev/artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/[1068 characters which appear to be a url base64 encoded signature and is assumed to authorize the get of the layer blob] [body redacted: omitting binary blobs from logs]
2020/12/21 18:14:31 GET /artifacts-downloads/namespaces/neuspaces/repositories/neuspaces/downloads/[1068 characters which appear to be a url base64 encoded signature and is assumed to authorize the get of the layer blob] HTTP/1.1
Host: europe-west3-docker.pkg.dev
User-Agent: go-containerregistry
Authorization: <redacted>
Referer: https://europe-west3-docker.pkg.dev/v2/neuspaces/neuspaces/go-httpbin/blobs/sha256:24f0c933cbef83faee52f82c7f889c727b1ece5123b92d036c52fa865480f037
Accept-Encoding: gzip
```

### Proposed changes

- Modify the response from the upstream AR as outlined in the description
- Optional: Introduce a flag to toggle this behavior (`GCP_AR_BLOB_BYPASS_PROXY`)

**Comment by christidis** [comment]
Did this close due to inactivity? Along with the PR https://github.com/ahmetb/serverless-registry-proxy/pull/9
Google Artifact Registry is marked as the next generation registry so this is quite important.
@ahmetb any chance you revisit this merge?

**Comment by ahmetb** [comment]
Happy to. I have not had the chance to review, apparently I accidentally muted my own repo for a year.
